name: On merge request

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 💿 Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 👮‍♂️ Validate commits semantic
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: 🕵 Lint the code
        run: yarn lint

      - name: 🔬 Run unit tests
        run: yarn test:coverage

      - name: 🧰 Build code
        run: yarn build
